# Generated by Django 3.1.5 on 2022-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('no_of_cart', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('product_id', models.CharField(max_length=10)),
                ('qty', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=10)),
                ('pickuplocation', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('checkingavailability', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Catlog',
            fields=[
                ('no_of_catlogs', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('product_id', models.CharField(max_length=10)),
                ('qty', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=10)),
                ('pickuplocation', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='check_availability',
            fields=[
                ('no_of_requests', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('availability', models.CharField(max_length=10)),
                ('seller_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsCustomers',
            fields=[
                ('cust_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('query', models.CharField(db_column='Query', max_length=400)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
                ('no_of_queries', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(db_column='mobile_no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsSellers',
            fields=[
                ('no_of_queries', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('query', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mobileno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=40)),
                ('cust_phone_no', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('companyname', models.CharField(max_length=40)),
                ('cust_role', models.CharField(db_column='Cust_role', max_length=40)),
                ('lookingfor', models.CharField(max_length=40)),
                ('no_of_samples_viewed', models.IntegerField(db_column='No_of_samples_viewed')),
            ],
        ),
        migrations.CreateModel(
            name='Installers',
            fields=[
                ('team_leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_leader_name', models.CharField(max_length=40)),
                ('leaders_phone_no', models.CharField(max_length=10)),
                ('installers_address', models.CharField(db_column='Installers_address', max_length=300)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=10)),
                ('productname', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=10)),
                ('cust_name', models.CharField(db_column='Cust_name', max_length=40)),
                ('seller_id', models.CharField(max_length=10)),
                ('sellers_name', models.CharField(max_length=40)),
                ('needinstallers', models.CharField(max_length=10)),
                ('installers_phoneno', models.CharField(max_length=10)),
                ('installers_leader_name', models.CharField(max_length=40)),
                ('transporter_leaders_phoneno', models.CharField(max_length=10)),
                ('traporter_leaders_name', models.CharField(max_length=40)),
                ('dropaddress', models.CharField(max_length=300)),
                ('customer_phone_no', models.CharField(max_length=10)),
                ('total_price', models.IntegerField(db_column='Total_price')),
                ('date', models.DateField()),
                ('fifty_percent_payment', models.CharField(max_length=10)),
                ('hundred_percent_payment', models.CharField(max_length=10)),
                ('pickupaddress', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=40)),
                ('material', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('seller_id', models.IntegerField()),
                ('seller_phone_no', models.CharField(max_length=10)),
                ('seller_name', models.CharField(max_length=40)),
                ('cost', models.IntegerField()),
                ('pickup_location', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='boho/images')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDone',
            fields=[
                ('no_of_sales', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('seller_name', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=40)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('seller_phoneno', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phoneno', models.CharField(max_length=10)),
                ('default_pickup_address', models.CharField(db_column='default pickup address', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transporters',
            fields=[
                ('team_leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_leader_name', models.CharField(max_length=40)),
                ('leaders_phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
