# Generated by Django 3.1.5 on 2022-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='availability',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='no_of_samples_viewed',
            field=models.IntegerField(db_column='No_of_samples_viewed', default='0'),
        ),
    ]
