# Generated by Django 3.1.5 on 2022-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boho', '0002_auto_20220310_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='availability',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
