# Generated by Django 3.1.5 on 2022-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boho', '0004_cart_totalcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('no_of_sponsors', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='boho/sponsorimages')),
            ],
        ),
    ]
