# Generated by Django 4.0.3 on 2022-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boho', '0006_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='boho/brandsimages')),
            ],
        ),
        migrations.RemoveField(
            model_name='offers',
            name='image_link',
        ),
        migrations.AddField(
            model_name='offers',
            name='image',
            field=models.ImageField(default='', upload_to='boho/offerimages'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
