# Generated by Django 4.0.3 on 2022-06-08 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boho', '0007_brands_remove_offers_image_link_offers_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='cust_phone_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
